name: bitsgap
description: Test task for bitsgap.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  another_flushbar: ^1.12.30
  easy_localization: ^3.0.3
  email_validator: ^2.1.17
  flutter:
    sdk: flutter
  flutter_mobx: ^2.1.0
  flutter_svg: ^2.0.7
  get_it: ^7.6.4
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  mobx: ^2.2.0
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mobx_codegen: ^2.4.0
  build_runner: ^2.4.6
  isar_generator: ^3.1.0+1


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/translations/

  fonts:
    - family: TT-Norms-Pro-Trial
      fonts:
        - asset: assets/fonts/TT Norms Pro Trial Regular.ttf
          weight: 400
        - asset: assets/fonts/TT Norms Pro Trial Medium.ttf
          weight: 500


