name: bitsgap
description: Test task for bitsgap.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  easy_localization: ^3.0.3
  email_validator: ^2.1.17
  flutter:
    sdk: flutter
  flutter_mobx: ^2.1.0
  flutter_svg: ^2.0.7
  mobx: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mobx_codegen: ^2.4.0
  build_runner: ^2.4.6


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/

  fonts:
    - family: TT-Norms-Pro-Trial
      fonts:
        - asset: assets/fonts/TT Norms Pro Trial Regular.ttf
          weight: 400
        - asset: assets/fonts/TT Norms Pro Trial Medium.ttf
          weight: 500


